Task.create(name: 'Laundry', description: "Do all laundry today", date: Time.now, checked: true)
Task.create(name: 'Dishes', description: "Do the dishes", date: Time.now, checked: false)
Task.create(name: 'Clean rooms', description: "Clean the bedrooms", date: Time.now, checked: true)
Task.create(name: 'Pay bills', description: "Pay electricy, water, cc bill", date: Time.now, checked: false)
Task.create(name: 'Garbage', description: "Dispose off the Garbage", date: Time.now, checked: true)
